### ISSUE TITLE
can rwmem-db be based off tcl

### ISSUE THREAD

**Issue by nmenon** [tomba/rwmem#4]
could rwmem-db be based on tcl?
this way, we might be able to share register definitions between openocd and rwmem for IP instances.

**Comment by tomba** [comment]
The rwmem-db is a binary file that can be directly mmapped and used without any parsing or processing. I don't want to change that, I want to keep things fast and with low overhead.

That said, those databases can of course be generated from "anything", like ipxact. Do you have an example of openocd's IP description? I couldn't find anything with a quick search.

**Comment by nmenon** [comment]
https://github.com/ntfreak/openocd/blob/master/tcl/target/am437x.cfg#L4 is an example -> it is a bit free form.. but kinda handy if the same data is used by both rwmem and openocd (jtag and external host based). also note that jimtcl used by openocd is pretty fast and been very useful for umpteen platforms (including integration with eclipse)

**Comment by tomba** [comment]
All that looks more like scripts for the environment, rather than register & field data. And afaics, it's really just setting variables with the register offsets, rather than describing register blocks.

Are you thinking about somehow just getting the registers & fields from the tcl, or actually running the tcl scripts with librwmem doing the reads & writes, similar to what we can already do with python?

For the former, I don't know how that could be accomplished from the script you linked. How to guess which ones are registers? For the latter, isn't openocd doing much more than just memory reads/writes (like jtag stuff). None of that can be done with rwmem.

**Comment by nmenon** [comment]
Just a common description database is all I was thinking.

---
Regards,
Nishanth Menon

**Comment by tomba** [comment]
I don't see how this could be done, so closing
